import type { ConverterDef, Engine, Ambition, ConverterStatus, InputMode, GroupSlug } from "./types";

type PartialConv = {
  from: string;
  to: string;
  group: GroupSlug;
  subgroup?: string;
  engine: Engine;
  ambition?: Ambition;
  status?: ConverterStatus;
  inputMode?: InputMode;
  accept?: string;
  maxBytes?: number;
  maxDurationSec?: number;
  popular?: boolean;
  notes?: string;
  description?: string;
  bidirectional?: boolean;
};

function slugPair(from: string, to: string) {
  const f = from.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  const t = to.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  return { forward: `${f}-to-${t}`, reverse: `${t}-to-${f}` };
}

function make(p: PartialConv): ConverterDef[] {
  const { forward, reverse } = slugPair(p.from, p.to);
  const ambition = p.ambition ?? "core";
  const status = p.status ?? (ambition === "stretch" ? "coming-soon" : "live");
  const inputMode = p.inputMode ?? "file";
  const base = {
    group: p.group,
    subgroup: p.subgroup,
    engine: p.engine,
    ambition,
    status,
    inputMode,
    accept: p.accept,
    maxBytes: p.maxBytes,
    maxDurationSec: p.maxDurationSec,
    popular: p.popular,
    notes: p.notes,
  };

  const forwardDef: ConverterDef = {
    ...base,
    id: `${p.group}/${forward}`,
    slug: forward,
    title: `${p.from} to ${p.to}`,
    description:
      p.description ?? `Convert ${p.from} to ${p.to} in your browser. Files stay on your device.`,
    from: p.from,
    to: p.to,
    reverseSlug: p.bidirectional === false ? undefined : reverse,
  };

  if (p.bidirectional === false) return [forwardDef];

  const reverseDef: ConverterDef = {
    ...base,
    id: `${p.group}/${reverse}`,
    slug: reverse,
    title: `${p.to} to ${p.from}`,
    description: `Convert ${p.to} to ${p.from} in your browser. Files stay on your device.`,
    from: p.to,
    to: p.from,
    reverseSlug: forward,
    popular: false,
    accept: acceptForFormat(p.to),
  };

  return [forwardDef, reverseDef];
}

function one(
  from: string,
  to: string,
  group: GroupSlug,
  engine: Engine,
  extra: Omit<PartialConv, "from" | "to" | "group" | "engine"> = {},
): ConverterDef[] {
  return make({ from, to, group, engine, ...extra });
}

function acceptForFormat(format: string): string | undefined {
  const key = format.toLowerCase();
  const map: Record<string, string> = {
    epub: ".epub,application/epub+zip",
    pdf: ".pdf,application/pdf",
    mobi: ".mobi",
    azw3: ".azw3",
    fb2: ".fb2,application/x-fictionbook+xml",
    cbz: ".cbz,application/vnd.comicbook+zip",
    docx: ".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    odt: ".odt,application/vnd.oasis.opendocument.text",
    pptx: ".pptx,application/vnd.openxmlformats-officedocument.presentationml.presentation",
    xlsx: ".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    latex: ".tex,.latex,text/x-tex",
    djvu: ".djvu,.djv,image/vnd.djvu",
    avif: "image/avif,.avif",
    parquet: ".parquet,application/vnd.apache.parquet",
    png: "image/png,.png",
    jpg: "image/jpeg,.jpg,.jpeg",
    jpeg: "image/jpeg,.jpg,.jpeg",
    webp: "image/webp,.webp",
    svg: "image/svg+xml,.svg",
    heic: ".heic,.heif,image/heic",
    mp4: "video/mp4,.mp4",
    webm: "video/webm,.webm",
    mov: "video/quicktime,.mov",
    mkv: "video/x-matroska,.mkv",
    mp3: "audio/mpeg,.mp3",
    wav: "audio/wav,.wav",
    srt: ".srt,text/plain",
    vtt: ".vtt,text/vtt",
    json: ".json,application/json,text/plain",
    yaml: ".yaml,.yml,text/yaml,text/plain",
    toml: ".toml,text/plain",
    xml: ".xml,text/xml,text/plain",
    csv: ".csv,text/csv",
    zip: ".zip,application/zip",
  };
  return map[key];
}

/** Full catalog — live where implementable; stretch/coming-soon listed for SEO. */
export const CONVERTERS: ConverterDef[] = [
  // ——— Documents ———
  ...one("EPUB", "PDF", "documents", "client", {
    subgroup: "Ebooks",
    popular: true,
    bidirectional: false,
    accept: ".epub,application/epub+zip",
    notes: "Owned in-browser conversion (text-forward). Files never leave your device.",
  }),
  ...one("MOBI", "EPUB", "documents", "client", {
    subgroup: "Ebooks",
    accept: ".mobi",
    notes:
      "Unprotected MOBI only (no DRM). Text-forward PalmDB scrape → EPUB; layout and images are limited.",
  }),
  ...one("AZW3", "EPUB", "documents", "client", {
    subgroup: "Ebooks",
    accept: ".azw3",
    notes:
      "Unprotected AZW3/KF8 only (no DRM). Best-effort text extraction → EPUB; not a Calibre-quality clone.",
  }),
  ...one("FB2", "EPUB", "documents", "client", {
    subgroup: "Ebooks",
    accept: ".fb2,application/x-fictionbook+xml",
    notes: "FictionBook XML ↔ EPUB chapters. Text-forward; complex markup may be flattened.",
  }),
  ...one("PDF", "EPUB", "documents", "client", {
    subgroup: "Ebooks",
    bidirectional: false,
    accept: ".pdf,application/pdf",
    notes: "Owned in-browser text extraction → EPUB. Layout fidelity is limited.",
  }),
  ...one("CBZ", "PDF", "documents", "client", {
    subgroup: "Comics",
    accept: ".cbz,application/vnd.comicbook+zip",
    notes:
      "CBZ (zipped images) ↔ PDF. PDF→CBZ embeds images when present, otherwise renders text pages to PNGs.",
  }),
  ...one("PDF", "DOCX", "documents", "client", {
    subgroup: "Office",
    accept: ".pdf,application/pdf",
    notes: "Text-forward PDF ↔ DOCX. No layout recreation; images/tables are not preserved.",
  }),
  ...one("DOCX", "ODT", "documents", "client", {
    subgroup: "Office",
    accept:
      ".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    notes: "Text-forward DOCX ↔ ODT via mammoth / minimal ODT ZIP. Styling is not preserved.",
  }),
  ...one("PPTX", "PDF", "documents", "client", {
    subgroup: "Office",
    bidirectional: false,
    accept:
      ".pptx,application/vnd.openxmlformats-officedocument.presentationml.presentation",
    notes: "Extracts slide text into a paginated PDF. Images and exact layout are not preserved.",
  }),
  ...one("XLSX", "PDF", "documents", "client", {
    subgroup: "Office",
    bidirectional: false,
    accept:
      ".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    notes: "Renders each sheet as CSV-like text in a PDF. Charts/formatting are not preserved.",
  }),
  ...one("LaTeX", "PDF", "documents", "client", {
    subgroup: "Office",
    bidirectional: false,
    inputMode: "both",
    accept: ".tex,.latex,text/x-tex,text/plain",
    notes:
      "LaTeX → HTML (latex.js) when possible, else command-stripped text → PDF. Not a full TeX engine.",
  }),
  ...one("DjVu", "PDF", "documents", "client", {
    subgroup: "Office",
    accept: ".djvu,.djv,image/vnd.djvu",
    notes:
      "Best-effort: extracts text/embedded images from DjVu → PDF; PDF→DjVu writes a minimal text-layer DjVu (no JB2/IW44 encoder).",
  }),
  {
    id: "documents/pdf-merge",
    slug: "pdf-merge",
    title: "Merge PDFs",
    description: "Combine multiple PDF files into one in your browser.",
    group: "documents",
    subgroup: "PDF toolkit",
    from: "PDF",
    to: "PDF",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "file",
    accept: ".pdf,application/pdf",
    popular: true,
  },
  {
    id: "documents/pdf-split",
    slug: "pdf-split",
    title: "Split PDF",
    description: "Extract pages from a PDF into a new file in your browser.",
    group: "documents",
    subgroup: "PDF toolkit",
    from: "PDF",
    to: "PDF",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "file",
    accept: ".pdf,application/pdf",
  },
  ...one("Images", "PDF", "documents", "client", {
    subgroup: "PDF toolkit",
    bidirectional: false,
    accept: "image/png,image/jpeg,.png,.jpg,.jpeg",
    popular: true,
  }),
  ...one("Markdown", "HTML", "documents", "client", {
    subgroup: "Markup",
    inputMode: "both",
    popular: true,
  }),
  ...one("Markdown", "PDF", "documents", "client", {
    subgroup: "Markup",
    bidirectional: false,
    inputMode: "both",
  }),
  ...one("TXT", "PDF", "documents", "client", {
    subgroup: "Markup",
    bidirectional: false,
    inputMode: "both",
  }),

  // ——— Images ———
  ...one("PNG", "JPG", "images", "client", {
    subgroup: "Format",
    popular: true,
    accept: "image/png,.png",
  }),
  ...one("PNG", "WebP", "images", "client", {
    subgroup: "Format",
    accept: "image/png,.png",
  }),
  ...one("JPG", "WebP", "images", "client", {
    subgroup: "Format",
    accept: "image/jpeg,.jpg,.jpeg",
  }),
  ...one("SVG", "PNG", "images", "client", {
    subgroup: "Format",
    bidirectional: false,
    accept: "image/svg+xml,.svg",
  }),
  ...one("HEIC", "JPG", "images", "client", {
    subgroup: "Format",
    bidirectional: false,
    accept: ".heic,.heif,image/heic,image/heif",
  }),
  {
    id: "images/image-to-base64",
    slug: "image-to-base64",
    title: "Image to Base64",
    description: "Encode an image as a Base64 data URL in your browser.",
    group: "images",
    subgroup: "Tools",
    from: "Image",
    to: "Base64",
    reverseSlug: "base64-to-image",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "file",
    accept: "image/*",
  },
  {
    id: "images/base64-to-image",
    slug: "base64-to-image",
    title: "Base64 to Image",
    description: "Decode a Base64 data URL into a downloadable image.",
    group: "images",
    subgroup: "Tools",
    from: "Base64",
    to: "Image",
    reverseSlug: "image-to-base64",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
  },
  {
    id: "images/resize-image",
    slug: "resize-image",
    title: "Resize image",
    description: "Resize and compress images in your browser.",
    group: "images",
    subgroup: "Tools",
    from: "Image",
    to: "Image",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "file",
    accept: "image/*",
    popular: true,
  },
  {
    id: "images/qr-code",
    slug: "qr-code",
    title: "QR code generator",
    description: "Generate a QR code PNG from text or a URL.",
    group: "images",
    subgroup: "Generators",
    from: "Text",
    to: "QR",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
    popular: true,
  },
  {
    id: "images/favicon-pack",
    slug: "favicon-pack",
    title: "Favicon pack",
    description: "Generate multi-size favicon PNGs from an image.",
    group: "images",
    subgroup: "Generators",
    from: "Image",
    to: "ICO pack",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "file",
    accept: "image/*",
  },

  // ——— Audio & video (ffmpeg.wasm) ———
  ...one("MP4", "WebM", "audio-video", "ffmpeg", {
    subgroup: "Video",
    popular: true,
    accept: "video/mp4,.mp4",
    maxBytes: 80 * 1024 * 1024,
    maxDurationSec: 180,
  }),
  ...one("MOV", "MP4", "audio-video", "ffmpeg", {
    subgroup: "Video",
    bidirectional: false,
    accept: "video/quicktime,.mov",
    maxBytes: 80 * 1024 * 1024,
    maxDurationSec: 180,
  }),
  ...one("MKV", "MP4", "audio-video", "ffmpeg", {
    subgroup: "Video",
    bidirectional: false,
    accept: "video/x-matroska,.mkv",
    maxBytes: 80 * 1024 * 1024,
    maxDurationSec: 180,
  }),
  ...one("Video", "GIF", "audio-video", "ffmpeg", {
    subgroup: "Video",
    bidirectional: false,
    accept: "video/*,.mp4,.webm,.mov",
    maxBytes: 40 * 1024 * 1024,
    maxDurationSec: 30,
  }),
  {
    id: "audio-video/trim-video",
    slug: "trim-video",
    title: "Trim video",
    description: "Trim a short video clip in your browser with ffmpeg.wasm.",
    group: "audio-video",
    subgroup: "Video",
    from: "Video",
    to: "Video",
    engine: "ffmpeg",
    ambition: "core",
    status: "live",
    inputMode: "file",
    accept: "video/*,.mp4,.webm,.mov",
    maxBytes: 80 * 1024 * 1024,
    maxDurationSec: 180,
  },
  ...one("Video", "MP3", "audio-video", "ffmpeg", {
    subgroup: "Audio",
    bidirectional: false,
    popular: true,
    accept: "video/*,.mp4,.webm,.mov",
    maxBytes: 80 * 1024 * 1024,
    maxDurationSec: 180,
  }),
  ...one("MP3", "WAV", "audio-video", "ffmpeg", {
    subgroup: "Audio",
    accept: "audio/mpeg,.mp3",
    maxBytes: 50 * 1024 * 1024,
    maxDurationSec: 180,
  }),
  ...one("SRT", "VTT", "audio-video", "client", {
    subgroup: "Subtitles",
    inputMode: "both",
    accept: ".srt,text/plain",
  }),

  // ——— Archives ———
  {
    id: "archives/zip-create",
    slug: "zip-create",
    title: "Create ZIP",
    description: "Pack multiple files into a ZIP archive in your browser.",
    group: "archives",
    subgroup: "ZIP",
    from: "Files",
    to: "ZIP",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "file",
    popular: true,
  },
  {
    id: "archives/zip-extract",
    slug: "zip-extract",
    title: "Extract ZIP",
    description: "Browse and download files from a ZIP in your browser.",
    group: "archives",
    subgroup: "ZIP",
    from: "ZIP",
    to: "Files",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "file",
    accept: ".zip,application/zip",
  },

  // ——— Data ———
  ...one("JSON", "YAML", "data", "client", {
    subgroup: "Structured",
    inputMode: "text",
    popular: true,
  }),
  ...one("JSON", "TOML", "data", "client", { subgroup: "Structured", inputMode: "text" }),
  ...one("JSON", "XML", "data", "client", { subgroup: "Structured", inputMode: "text" }),
  ...one("JSON", "CSV", "data", "client", {
    subgroup: "Structured",
    inputMode: "both",
    popular: true,
  }),
  ...one("CSV", "XLSX", "data", "client", {
    subgroup: "Structured",
    bidirectional: false,
    inputMode: "file",
    accept: ".csv,text/csv",
  }),
  {
    id: "data/json-pretty",
    slug: "json-pretty",
    title: "Pretty-print JSON",
    description: "Validate and format JSON in your browser.",
    group: "data",
    subgroup: "Structured",
    from: "JSON",
    to: "JSON",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
  },
  {
    id: "data/query-to-json",
    slug: "query-to-json",
    title: "Query string to JSON",
    description: "Parse a URL query string into JSON.",
    group: "data",
    subgroup: "Structured",
    from: "Query",
    to: "JSON",
    reverseSlug: "json-to-query",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
  },
  {
    id: "data/json-to-query",
    slug: "json-to-query",
    title: "JSON to query string",
    description: "Serialize a flat JSON object to a query string.",
    group: "data",
    subgroup: "Structured",
    from: "JSON",
    to: "Query",
    reverseSlug: "query-to-json",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
  },

  // ——— Encoding ———
  {
    id: "encoding/base64",
    slug: "base64",
    title: "Base64 encode / decode",
    description: "Encode or decode Base64 text in your browser.",
    group: "encoding",
    subgroup: "Encode",
    from: "Text",
    to: "Base64",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
    popular: true,
  },
  {
    id: "encoding/url-encode",
    slug: "url-encode",
    title: "URL encode / decode",
    description: "Encode or decode URL components.",
    group: "encoding",
    subgroup: "Encode",
    from: "Text",
    to: "URL",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
  },
  {
    id: "encoding/html-encode",
    slug: "html-encode",
    title: "HTML encode / decode",
    description: "Escape or unescape HTML entities.",
    group: "encoding",
    subgroup: "Encode",
    from: "Text",
    to: "HTML entities",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
  },
  {
    id: "encoding/hash",
    slug: "hash",
    title: "Hash generator",
    description: "Compute SHA-256, SHA-512, SHA-1, and MD5 digests.",
    group: "encoding",
    subgroup: "Integrity",
    from: "Text",
    to: "Hash",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
    popular: true,
  },
  {
    id: "encoding/jwt-decode",
    slug: "jwt-decode",
    title: "JWT decode",
    description: "Inspect JWT header and payload (no signature forge).",
    group: "encoding",
    subgroup: "Integrity",
    from: "JWT",
    to: "JSON",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
  },
  {
    id: "encoding/uuid",
    slug: "uuid",
    title: "UUID generate / validate",
    description: "Generate or validate UUIDs.",
    group: "encoding",
    subgroup: "Integrity",
    from: "UUID",
    to: "UUID",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
  },
  {
    id: "encoding/number-base",
    slug: "number-base",
    title: "Number base converter",
    description: "Convert between binary, octal, decimal, and hex.",
    group: "encoding",
    subgroup: "Integrity",
    from: "Number",
    to: "Bases",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
  },

  // ——— Text ———
  {
    id: "text/case",
    slug: "case",
    title: "Case converter",
    description: "camelCase, snake_case, kebab-case, PascalCase, and more.",
    group: "text",
    subgroup: "Transform",
    from: "Text",
    to: "Case",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
    popular: true,
  },
  {
    id: "text/slugify",
    slug: "slugify",
    title: "Slugify",
    description: "Turn a title into a URL-safe slug.",
    group: "text",
    subgroup: "Transform",
    from: "Text",
    to: "Slug",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
  },
  {
    id: "text/word-count",
    slug: "word-count",
    title: "Word counter",
    description: "Count words, characters, lines, and reading time.",
    group: "text",
    subgroup: "Helpers",
    from: "Text",
    to: "Stats",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
  },
  ...one("HTML", "Markdown", "text", "client", {
    subgroup: "Transform",
    inputMode: "text",
  }),
  {
    id: "text/lorem",
    slug: "lorem",
    title: "Lorem ipsum",
    description: "Generate placeholder paragraphs.",
    group: "text",
    subgroup: "Helpers",
    from: "Lorem",
    to: "Text",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
  },
  {
    id: "text/diff",
    slug: "diff",
    title: "Text diff",
    description: "Compare two texts line by line.",
    group: "text",
    subgroup: "Helpers",
    from: "Text",
    to: "Diff",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
  },
  {
    id: "text/sort-lines",
    slug: "sort-lines",
    title: "Sort / dedupe lines",
    description: "Sort, reverse, or remove duplicate lines.",
    group: "text",
    subgroup: "Transform",
    from: "Text",
    to: "Text",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
  },

  // ——— Code ———
  {
    id: "code/json-minify",
    slug: "beautify-minify",
    title: "Beautify / minify",
    description: "Format or minify JSON, CSS, and HTML.",
    group: "code",
    subgroup: "Format",
    from: "Code",
    to: "Code",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
    popular: true,
  },
  {
    id: "code/meta-extractor",
    slug: "meta-extractor",
    title: "Meta / OG extractor",
    description: "Extract title, description, and Open Graph tags from HTML.",
    group: "code",
    subgroup: "Web",
    from: "HTML",
    to: "Meta",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
  },
  {
    id: "code/user-agent",
    slug: "user-agent",
    title: "User-agent parser",
    description: "Parse a user-agent string into readable fields.",
    group: "code",
    subgroup: "Web",
    from: "UA",
    to: "JSON",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
  },

  // ——— Design ———
  {
    id: "design/color",
    slug: "color",
    title: "Color converter",
    description: "Convert between HEX, RGB, HSL, and OKLCH.",
    group: "design",
    subgroup: "Color",
    from: "Color",
    to: "Color",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
    popular: true,
  },
  {
    id: "design/contrast",
    slug: "contrast",
    title: "Contrast checker",
    description: "Check WCAG contrast between two colors.",
    group: "design",
    subgroup: "Color",
    from: "Colors",
    to: "WCAG",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
  },
  {
    id: "design/gradient",
    slug: "gradient",
    title: "CSS gradient generator",
    description: "Build a CSS linear gradient and copy the code.",
    group: "design",
    subgroup: "CSS",
    from: "Colors",
    to: "CSS",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
  },
  {
    id: "design/aspect-ratio",
    slug: "aspect-ratio",
    title: "Aspect ratio helper",
    description: "Compute dimensions for common aspect ratios.",
    group: "design",
    subgroup: "Layout",
    from: "Size",
    to: "Ratio",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
  },

  // ——— Units ———
  {
    id: "units/temperature",
    slug: "temperature",
    title: "Temperature converter",
    description: "Convert between Celsius, Fahrenheit, and Kelvin.",
    group: "units",
    subgroup: "Physical",
    from: "Temp",
    to: "Temp",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
    popular: true,
  },
  {
    id: "units/length",
    slug: "length",
    title: "Length converter",
    description: "Convert meters, feet, inches, miles, and more.",
    group: "units",
    subgroup: "Physical",
    from: "Length",
    to: "Length",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
  },
  {
    id: "units/weight",
    slug: "weight",
    title: "Weight converter",
    description: "Convert kilograms, pounds, ounces, and stones.",
    group: "units",
    subgroup: "Physical",
    from: "Weight",
    to: "Weight",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
  },
  {
    id: "units/data-size",
    slug: "data-size",
    title: "Data size converter",
    description: "Convert between B, KB, KiB, MB, MiB, GB, and GiB.",
    group: "units",
    subgroup: "Physical",
    from: "Bytes",
    to: "Bytes",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
  },
  {
    id: "units/timestamp",
    slug: "timestamp",
    title: "Unix timestamp",
    description: "Convert between Unix timestamps and ISO dates.",
    group: "units",
    subgroup: "Time",
    from: "Unix",
    to: "ISO",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
    popular: true,
  },
  {
    id: "units/timezone",
    slug: "timezone",
    title: "Timezone converter",
    description: "Convert a time across common timezones.",
    group: "units",
    subgroup: "Time",
    from: "Time",
    to: "Zones",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
  },
  {
    id: "units/currency",
    slug: "currency",
    title: "Currency converter",
    description:
      "Convert currencies using live exchange rates (Frankfurter). Rate lookup only — math stays in-app.",
    group: "units",
    subgroup: "Money",
    from: "Currency",
    to: "Currency",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
    popular: true,
    notes: "Calls a rates API for supplementary FX data. Your files are never uploaded for conversion.",
  },
  {
    id: "units/cron",
    slug: "cron",
    title: "Cron explain",
    description: "Explain a 5-field cron expression in plain English.",
    group: "units",
    subgroup: "Time",
    from: "Cron",
    to: "Text",
    engine: "client",
    ambition: "core",
    status: "live",
    inputMode: "text",
  },

  // ——— Images / data (formerly stretch) ———
  ...one("AVIF", "PNG", "images", "client", {
    subgroup: "Format",
    notes:
      "Browser canvas encode/decode. Requires AVIF support in the runtime; fidelity matches the browser encoder.",
  }),
  ...one("Parquet", "CSV", "data", "client", {
    subgroup: "Structured",
    inputMode: "both",
    accept: ".parquet,application/vnd.apache.parquet",
    notes: "hyparquet read / hyparquet-writer write. Nested types are flattened to CSV cells.",
  }),
];

export function getConverter(group: string, slug: string): ConverterDef | undefined {
  return CONVERTERS.find((c) => c.group === group && c.slug === slug);
}

export function convertersByGroup(group: string): ConverterDef[] {
  return CONVERTERS.filter((c) => c.group === group);
}

export function popularConverters(): ConverterDef[] {
  return CONVERTERS.filter((c) => c.popular && c.status === "live");
}

export function searchConverters(query: string): ConverterDef[] {
  const q = query.trim().toLowerCase();
  if (!q) return CONVERTERS;
  return CONVERTERS.filter((c) => {
    const hay = `${c.title} ${c.from} ${c.to} ${c.description} ${c.subgroup ?? ""} ${c.group}`.toLowerCase();
    return hay.includes(q);
  });
}

export function converterHref(c: ConverterDef): string {
  return `/${c.group}/${c.slug}`;
}
